In [2]:
# Generate matrix:

###    1  2  3  4  5
###    6  7  8  9 10
###   11 12 13 14 15
###   16 17 18 19 20
###   21 22 23 24 25
###   26 27 28 29 30

# Acces 
#        11 12
#        16 17
    
# Acces  
#         2
#           8
#            14
#              20

# Acces        
#                4  5



#               24 25
#               29 30

In [3]:
import numpy as np
a=np.matrix(np.arange(1,31).reshape(6,5))
print(a)
print(a[2:4,:2])
b=np.matrix(np.zeros(4).reshape(1,4))
for i in range(4):
    b[0,i]=a[i,i+1]
print(b)
print(a[0,3:])
print(a[4:,3:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
[[11 12]
 [16 17]]
[[ 2.  8. 14. 20.]]
[[4 5]]
[[24 25]
 [29 30]]
